# Generated by Django 3.1.6 on 2021-02-21 13:18

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import orderapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.FileField(upload_to='files/user_avatar', validators=[orderapp.models.validate_file_extension])),
                ('description', models.CharField(max_length=512)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('cover', models.FileField(upload_to='files/product_cover', validators=[orderapp.models.validate_file_extension])),
                ('price', models.IntegerField(default=0)),
                ('description', models.CharField(max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('promote', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OrderApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orderapp.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orderapp.product')),
            ],
        ),
    ]
