# Generated by Django 3.1.6 on 2021-02-24 18:11

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import orderapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.FileField(upload_to='user_avatar', validators=[orderapp.models.validate_file_extension], verbose_name='عکس')),
                ('description', ckeditor.fields.RichTextField(verbose_name='توضیحات')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتریان',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('cover', models.FileField(default='temp.jpg', upload_to='product_cover', validators=[orderapp.models.validate_file_extension], verbose_name='کاور کالا')),
                ('price', models.IntegerField(default=0, verbose_name='قیمت')),
                ('description', ckeditor.fields.RichTextField(verbose_name='توضیحات')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('promote', models.BooleanField(default=False, verbose_name='تبلیغات')),
            ],
            options={
                'verbose_name': 'کالا',
                'verbose_name_plural': 'کالاها',
            },
        ),
        migrations.CreateModel(
            name='OrderApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
                ('price', models.IntegerField(default=0)),
                ('tedad', models.IntegerField(default=0)),
                ('price_all', models.BigIntegerField(default=0)),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('description', ckeditor.fields.RichTextField(verbose_name='توضیحات')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orderapp.customer', verbose_name='مشتری')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orderapp.product', verbose_name='کالا')),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'سفارشات',
            },
        ),
    ]
