# Generated by Django 3.1.6 on 2021-02-22 09:13

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import orderapp.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orderapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'مشتری', 'verbose_name_plural': 'مشتریان'},
        ),
        migrations.AlterModelOptions(
            name='orderapp',
            options={'verbose_name': 'سفارش', 'verbose_name_plural': 'سفارشات'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'کالا', 'verbose_name_plural': 'کالاها'},
        ),
        migrations.AddField(
            model_name='orderapp',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderapp',
            name='price_all',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderapp',
            name='tedad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='avatar',
            field=models.FileField(upload_to='files/user_avatar', validators=[orderapp.models.validate_file_extension], verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='description',
            field=models.CharField(max_length=512, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='orderapp',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='orderapp',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orderapp.customer', verbose_name='مشتری'),
        ),
        migrations.AlterField(
            model_name='orderapp',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='orderapp',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orderapp.product', verbose_name='کالا'),
        ),
        migrations.AlterField(
            model_name='orderapp',
            name='title',
            field=models.CharField(max_length=50, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='orderapp',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cover',
            field=models.FileField(upload_to='files/product_cover', validators=[orderapp.models.validate_file_extension], verbose_name='عکس محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='create_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(max_length=50, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='product',
            name='promote',
            field=models.BooleanField(default=False, verbose_name='تبلیغات'),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=50, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='product',
            name='update_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش'),
        ),
    ]
