# Generated by Django 3.1.6 on 2021-02-25 05:36

from django.db import migrations, models
import orderapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='avatar',
            field=models.FileField(blank=True, default='temp.jpg', null=True, upload_to='user_avatar', validators=[orderapp.models.validate_file_extension], verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cover',
            field=models.FileField(blank=True, default='temp.jpg', null=True, upload_to='product_cover', validators=[orderapp.models.validate_file_extension], verbose_name='کاور کالا'),
        ),
    ]
