# Generated by Django 3.1.6 on 2021-02-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0002_auto_20210219_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderapp',
            name='promote',
            field=models.BooleanField(default=False),
        ),
    ]
