# Generated by Django 3.1.6 on 2021-02-19 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0006_product_create_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderapp',
            name='promote',
        ),
        migrations.AddField(
            model_name='product',
            name='promote',
            field=models.BooleanField(default=False),
        ),
    ]
